//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parshvnath
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaDetail
    {
        public AreaDetail()
        {
            this.SubAreaDetails = new HashSet<SubAreaDetail>();
            this.HoardingMasters = new HashSet<HoardingMaster>();
        }
    
        public int ID { get; set; }
        public int CityID { get; set; }
        public string Area { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CityDetail CityDetail { get; set; }
        public virtual ICollection<SubAreaDetail> SubAreaDetails { get; set; }
        public virtual ICollection<HoardingMaster> HoardingMasters { get; set; }
    }
}
