//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parshvnath
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoardingMaster
    {
        public HoardingMaster()
        {
            this.HoardingHistories = new HashSet<HoardingHistory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> SubAreaID { get; set; }
        public Nullable<int> HoardingNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string HoardingSize { get; set; }
    
        public virtual AreaDetail AreaDetail { get; set; }
        public virtual CityDetail CityDetail { get; set; }
        public virtual ICollection<HoardingHistory> HoardingHistories { get; set; }
    }
}
