//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parshvnath
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAreaDetail
    {
        public int ID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string SubArea { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual AreaDetail AreaDetail { get; set; }
    }
}
